//Even Fibonacci numbers
/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
#include <iostream>

int main(){
	//variables for the last two terms
	//variable for max number
	//variable for total sum
	
	//use a while loop to loop to 4mill
	//add t1 and t2 -> t3?
	//set t1=t2, t2=t3
	
	constexpr int max {4000000};
	int total{2};
	int t1{1}; //first term
	int t2{2}; //second term
	int t3{}; //third (last) term
	
	//while the highest number is less than the maximum
	while(t2 <= max){
		
		//create newest (3rd) term
		t3=t1+t2;
		
		//if new value is even, add to total
		if ((t3%2)==0){
			total+=t3;
		}

		t1=t2; //set the new 1st term
		t2=t3; //set the new 2nd term
		
	}
	 
	std::cout << "total: " << total << '\n';
	
}
